---
- name: Update and upgrade servers
  hosts: shaun,wallace
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
